dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6
    - postgresql-contrib-9.6
    - postgresql-9.6-postgis-scripts
env:
  global:
    - PGPORT="5432"
    - DJANGO_SECRET_KEY="testing"
    - DATABASE_NAME="travis_ci_testing"
before_script:
  - psql -c 'create database travis_ci_testing;' -U postgres
  - psql -c 'create extension postgis;' -d travis_ci_testing -U postgres
install:
  - pip install -r .requirements/testing.txt
script:
  - python app/manage.py test app/tests
after_success:
  - coveralls
